### ISSUE TITLE
Matlab版报错，请教一下

### ISSUE THREAD

**Issue by LegendZX** [QuantBox/CTP#12]
打包下载的5月25日更新的Matlab .Net版，更改本地目录，运行后出现如下错误：

Error using test (line 11)
Message: 无法加载 DLL“QuantBox.C2CTP.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
Source: QuantBox.CSharp2CTP

尝试添加代码 NET.addAssembly(fullfile(cd,'QuantBox.C2CTP.dll')); 在文件头，运行后出现如下错误：

Error using test (line 5)
Message: 未能加载文件或程序集“file:///G:\MATLABCTP\QuantBox.C2CTP.dll”或它的某一个依赖项。该模块应包含一个程序集清单。
Source: mscorlib

想请教一下应当如何解决？本人使用的Matlab版本为2012a

谢谢！

**Comment by wukan1986** [comment]
1.确保你的Matlab是32位版
2.下载depends，打开QuantBox.C2CTP.dll，确保依赖项正常

**Comment by LegendZX** [comment]
嗯，问题解决了，感谢！

用depends打开发现缺失了 msvcp120.dll, ieshims.dll wer.dll

下载补全之后F5通过

**Comment by bearzx** [comment]
LZ的matlab code在win8.1上测试过吗。我在win8.1上始终run不通，用depends查发现是缺API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL，但是下载了放到system32里还是不行。

貌似是win8.1的core problem ?

**Comment by wukan1986** [comment]
如果实在不行，请使用VS2103重新编译QuantBox.C2CTP这个项目
