### ISSUE TITLE
我想知道你们的CTP的程序接口是从那里下载的

### ISSUE THREAD

**Issue by nooperpudd** [QuantBox/CTP#13]
我也想写一个多语言动态的封装，但是对比了很多版本，发现都又不大一样的地方。
希望能够找到一份官方的CTP接口，最新的版本。

**Comment by wukan1986** [comment]
http://www.sfit.com.cn/5_2_DocumentDown.htm

**Comment by nooperpudd** [comment]
@wukan1986  thanks.
