### ISSUE TITLE
[java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。

### ISSUE THREAD

**Issue by zjulzq** [QuantBox/CTP#5]
我运行的时候，一直是这个问题。
我没有改变你项目的目录结构，直接git clone下来，然后导入eclipse。
QuartBox.C2CTP.dll在项目的根目录下，可是它一直报这个错。
请问这是怎么回事呀？你有遇到过吗？

**Comment by wukan1986** [comment]
请下载depends并检查哪些dll缺少

**Comment by zjulzq** [comment]
工程目录下有3个dll，分别是QuantBox.C2CTP.dll, thostmduserapi.dll,thosttraderapi.dll.
我直接clone你的项目的呀，里面少了什么depends呀？
按照README来操作的，还是找不到QuantBox.C2CTP。

**Comment by wukan1986** [comment]
我哪知道你电脑中少了啥啊！我让你下工具就让你自己找到少了啥

**Comment by solobear** [comment]
java版本的话，很有可能是64位java的问题。

改成32位的java和ecliplise，就可以了。。。我试过。

------------------ 原始邮件 ------------------
发件人: "伍侃";notifications@github.com;
发送时间: 2013年11月24日(星期天) 晚上9:44
收件人: "QuantBox/CTP"CTP@noreply.github.com; 

主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

我哪知道你电脑中少了啥啊！我让你下工具就让你自己找到少了啥

**Comment by zjulzq** [comment]
@solobear 我的是64位的呢。你的方案也许可行，我试试。

**Comment by zjulzq** [comment]
@wukan1986 一般来说，从git上clone的项目都是完整的呢，不会少东西的。

**Comment by zjulzq** [comment]
@solobear 我先试试你的方案，如果是位数的问题的话，我尝试下弄成64位系统的。

**Comment by AndreasZou** [comment]
关于这个64位的问题，我测试过。java64位，是不行的。请问一下，能不能升级成64位的系统也可以呢？

**Comment by AndreasZou** [comment]
还有一个问题是，CTP的测试环境是不是只是在交易日交易时段才能进行测试呢？

**Comment by solobear** [comment]
请明白：64位的问题，只是我作为一个与CTP和OQ毫无关系的过来人的友善提醒。。。
本人没有“义务”给你提供任何其它帮助，也许Quantbox也没有，开源的地带，需要大家共同的努力，而不仅仅是“伸手主义”！

64位的问题，如果你真的研究过，就会发现这是CTP接口本身的问题。。。不想多说了。。。此贴不再回复，见谅。

------------------ 原始邮件 ------------------
发件人: "AndreasZou";notifications@github.com;
发送时间: 2013年12月1日(星期天) 下午4:33
收件人: "QuantBox/CTP"CTP@noreply.github.com; 
抄送: "所罗熊"156709038@qq.com; 
主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

关于这个64位的问题，我测试过。java64位，是不行的。请问一下，能不能升级成64位的系统也可以呢？

**Comment by AndreasZou** [comment]
solobear，你好：
第一，很感激你的回复，如果64位是CTP接口本身的问题，那么可能就要想另外的方法去解决了。
第二，必须要澄清一点，我觉得你误会我的意思，也太过绝对了。我是提出一个问题，“能不能升级成64位”，并没有任何所谓的“伸手主意”，其实只是简简单单一个回复，为什么就要讨论到“权利”、“义务”。

在 2013-12-01 17:53:07，solobear notifications@github.com 写道：
请明白：64位的问题，只是我作为一个与CTP和OQ毫无关系的过来人的友善提醒。。。
本人没有“义务”给你提供任何其它帮助，也许Quantbox也没有，开源的地带，需要大家共同的努力，而不仅仅是“伸手主义”！

64位的问题，如果你真的研究过，就会发现这是CTP接口本身的问题。。。不想多说了。。。此贴不再回复，见谅。

------------------ 原始邮件 ------------------
发件人: "AndreasZou";notifications@github.com;
发送时间: 2013年12月1日(星期天) 下午4:33
收件人: "QuantBox/CTP"CTP@noreply.github.com;
抄送: "所罗熊"156709038@qq.com;
主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

关于这个64位的问题，我测试过。java64位，是不行的。请问一下，能不能升级成64位的系统也可以呢？

**Comment by solobear** [comment]
好吧，我也过激了！sorry！

关于64位的问题，个人觉得：
1. Win32：   显而易见的没问题。
1. Win64：   Win64 + Java32 + CTP32 可以运行。
2. Lin：    32/64位都没有问题，CTP在Lin上提供了两个版本。

------------------ 原始邮件 ------------------
发件人: "AndreasZou";notifications@github.com;
发送时间: 2013年12月2日(星期一) 晚上10:48
收件人: "QuantBox/CTP"CTP@noreply.github.com; 
抄送: "所罗熊"156709038@qq.com; 
主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

solobear，你好：
 第一，很感激你的回复，如果64位是CTP接口本身的问题，那么可能就要想另外的方法去解决了。
 第二，必须要澄清一点，我觉得你误会我的意思，也太过绝对了。我是提出一个问题，“能不能升级成64位”，并没有任何所谓的“伸手主意”，其实只是简简单单一个回复，为什么就要讨论到“权利”、“义务”。

 在 2013-12-01 17:53:07，solobear notifications@github.com 写道：
 请明白：64位的问题，只是我作为一个与CTP和OQ毫无关系的过来人的友善提醒。。。
 本人没有“义务”给你提供任何其它帮助，也许Quantbox也没有，开源的地带，需要大家共同的努力，而不仅仅是“伸手主义”！

 64位的问题，如果你真的研究过，就会发现这是CTP接口本身的问题。。。不想多说了。。。此贴不再回复，见谅。

 ------------------ 原始邮件 ------------------
 发件人: "AndreasZou";notifications@github.com;
 发送时间: 2013年12月1日(星期天) 下午4:33
 收件人: "QuantBox/CTP"CTP@noreply.github.com;
 抄送: "所罗熊"156709038@qq.com;
 主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

 关于这个64位的问题，我测试过。java64位，是不行的。请问一下，能不能升级成64位的系统也可以呢？

**Comment by AndreasZou** [comment]
好的，感谢你；关键是java，看来得想个办法才行~~

在 2013-12-02 22:53:53，solobear notifications@github.com 写道：
好吧，我也过激了！sorry！

关于64位的问题，个人觉得：
1. Win32： 显而易见的没问题。
1. Win64： Win64 + Java32 + CTP32 可以运行。
2. Lin： 32/64位都没有问题，CTP在Lin上提供了两个版本。

------------------ 原始邮件 ------------------
发件人: "AndreasZou";notifications@github.com;
发送时间: 2013年12月2日(星期一) 晚上10:48
收件人: "QuantBox/CTP"CTP@noreply.github.com;
抄送: "所罗熊"156709038@qq.com;
主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

solobear，你好：
第一，很感激你的回复，如果64位是CTP接口本身的问题，那么可能就要想另外的方法去解决了。
第二，必须要澄清一点，我觉得你误会我的意思，也太过绝对了。我是提出一个问题，“能不能升级成64位”，并没有任何所谓的“伸手主意”，其实只是简简单单一个回复，为什么就要讨论到“权利”、“义务”。

在 2013-12-01 17:53:07，solobear notifications@github.com 写道：
请明白：64位的问题，只是我作为一个与CTP和OQ毫无关系的过来人的友善提醒。。。
本人没有“义务”给你提供任何其它帮助，也许Quantbox也没有，开源的地带，需要大家共同的努力，而不仅仅是“伸手主义”！

64位的问题，如果你真的研究过，就会发现这是CTP接口本身的问题。。。不想多说了。。。此贴不再回复，见谅。

------------------ 原始邮件 ------------------
发件人: "AndreasZou";notifications@github.com;
发送时间: 2013年12月1日(星期天) 下午4:33
收件人: "QuantBox/CTP"CTP@noreply.github.com;
抄送: "所罗熊"156709038@qq.com;
主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

关于这个64位的问题，我测试过。java64位，是不行的。请问一下，能不能升级成64位的系统也可以呢？

**Comment by solobear** [comment]
想什么办法？

可以同时装32和64位的java嘛。

------------------ 原始邮件 ------------------
发件人: "AndreasZou";notifications@github.com;
发送时间: 2013年12月2日(星期一) 晚上10:56
收件人: "QuantBox/CTP"CTP@noreply.github.com; 
抄送: "所罗熊"156709038@qq.com; 
主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)

好的，感谢你；关键是java，看来得想个办法才行~~

 在 2013-12-02 22:53:53，solobear notifications@github.com 写道：
 好吧，我也过激了！sorry！

 关于64位的问题，个人觉得：
1. Win32： 显而易见的没问题。
2. Win64： Win64 + Java32 + CTP32 可以运行。
3. Lin： 32/64位都没有问题，CTP在Lin上提供了两个版本。
   
   ------------------ 原始邮件 ------------------
   发件人: "AndreasZou";notifications@github.com;
   发送时间: 2013年12月2日(星期一) 晚上10:48
   收件人: "QuantBox/CTP"CTP@noreply.github.com;
   抄送: "所罗熊"156709038@qq.com;
   主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)
   
   solobear，你好：
   第一，很感激你的回复，如果64位是CTP接口本身的问题，那么可能就要想另外的方法去解决了。
   第二，必须要澄清一点，我觉得你误会我的意思，也太过绝对了。我是提出一个问题，“能不能升级成64位”，并没有任何所谓的“伸手主意”，其实只是简简单单一个回复，为什么就要讨论到“权利”、“义务”。
   
   在 2013-12-01 17:53:07，solobear notifications@github.com 写道：
   请明白：64位的问题，只是我作为一个与CTP和OQ毫无关系的过来人的友善提醒。。。
   本人没有“义务”给你提供任何其它帮助，也许Quantbox也没有，开源的地带，需要大家共同的努力，而不仅仅是“伸手主义”！
   
   64位的问题，如果你真的研究过，就会发现这是CTP接口本身的问题。。。不想多说了。。。此贴不再回复，见谅。
   
   ------------------ 原始邮件 ------------------
   发件人: "AndreasZou";notifications@github.com;
   发送时间: 2013年12月1日(星期天) 下午4:33
   收件人: "QuantBox/CTP"CTP@noreply.github.com;
   抄送: "所罗熊"156709038@qq.com;
   主题: Re: [CTP] [java]Unable to load library 'QuantBox.C2CTP': 找不到指定的模块。 (#5)
   
   关于这个64位的问题，我测试过。java64位，是不行的。请问一下，能不能升级成64位的系统也可以呢？
