### ISSUE TITLE
中文编码

### ISSUE THREAD

**Issue by zjulzq** [QuantBox/CTP#6]
在eclipse下，类里面的中文显示为这样的： \u7ec4\u5408\u4ea4\u6613\u5408\u7ea6\u7684\u5355\u817f

请问，应该将编码设置为什么呢？

我尝试过GBK、GB2312、UTF-8，都不管用。

**Comment by wukan1986** [comment]
工具生成的就是这样,你自己不确信时请自行使用记事本打开对照

**Comment by AndreasZou** [comment]
这个是Unicode编码，你可以用外部的Unicode解码工具解开
